### ISSUE TITLE
release a new version (so we can take advantage of the security update)

### ISSUE THREAD

**Issue by wmhilton** [karma-runner/karma-browserstack-launcher#135]

**Comment by daKmoR** [comment]
a simple
```
npm publish
```

should be enough right?
or is there anything we can help with?

**Comment by johnjbarton** [comment]
It seems like this npm package is owned by @dignifiedquire, rather than @karmarunnerbot used in our scripts to npm publish.

**Comment by guilhem88** [comment]
Is this why version 1.4.0 is not available on npmjs?

**Comment by johnjbarton** [comment]
I don't have permission to publish the package.

**Comment by dignifiedquire** [comment]
@johnjbarton you have now

**Comment by daKmoR** [comment]
sooo is it possible to get a release? or anything else blocking?

**Comment by johnjbarton** [comment]
I still cannot release:
```
npm ERR! You do not have permission to publish "karma-browserstack-launcher". Are you logged in as the correct user? : karma-browserstack-launcher
```
The instructions I use are here:
http://karma-runner.github.io/3.0/dev/maintaining.html
esp:  `npm login karmarunnerbot`

**Comment by mgol** [comment]
Only these people have publish rights:
```
$ npm owner ls karma-browserstack-launcher
dignifiedquire <dignifiedquire@gmail.com>
donato <venar303@gmail.com>
morethanreal <yvonne@extraonions.ca>
robwalch <rwalch@gmail.com>
vojtajina <vojta.jina+npm@gmail.com>
zzo <mark@zzo.com>
```

**Comment by gkatsev** [comment]
Looks like @johnjbarton should have access to publish as his own account, according to `npm access`:
```sh
$ npm access ls-collaborators karma-browserstack-launcher
{
  "morethanreal": "read-write",
  "robwalch": "read-write",
  "dignifiedquire": "read-write",
  "johnjbarton": "read-write",
  "zzo": "read-write",
  "vojtajina": "read-write",
  "donato": "read-write"
}
```

**Comment by gkatsev** [comment]
Also, would be great to get https://github.com/karma-runner/karma-browserstack-launcher/pull/138 pulled in as well before the release so that patch fixes can just be picked up automatically

**Comment by harrysarson** [comment]
Are there any updates on this one?

**Comment by sebavan** [comment]
Hello, as @harrysarson mentionned it has been 2 weeks, is it possible to have an update on the release ?

This our only package with npm audit issue in https://github.com/BabylonJS/Babylon.js and the worse is that it has already been fixed, just not deployed.

**Comment by BrandonOCasey** [comment]
@johnjbarton can you publish a release?

**Comment by kalamcs** [comment]
We (at Browserstack), are trying to connect with the collaborators, and get this published ASAP. Will update here once done.

Regards

**Comment by zzo** [comment]
@johnjbarton has as much permissions as I do to publish this - he's the current maintainer and will need to publish.  I have added 'karmarunnerbot' as a maintainer on npmjs as well.

**Comment by zzo** [comment]
also it's up to @johnjbarton to grant permissions to this repo not me sorry :) . maybe he's on vacation?

**Comment by agarwalswapnil** [comment]
Hi @johnjbarton , Happy New Year!
I was wondering if you can grant @kalamcs publish permissions for this repo and for npm.

**Comment by johnjbarton** [comment]
The npm and github-repo permissions are completely independent. I cannot publish to npm nor delegate that permission.  I've asked zzo@ to add me.

**Comment by BrandonOCasey** [comment]
@johnjbarton [As shown by @gkatsev above](https://github.com/karma-runner/karma-browserstack-launcher/issues/135#issuecomment-436312838) and running `npm access ls-collaborators karma-browserstack-launcher` again it seems that you should have permissions to publish. You should be able to. Try running `npm whoami` to see if you are logged in on the correct account.

**Comment by johnjbarton** [comment]
I've added @kalamcs to the github project and npm publish permissions.

**Comment by kalamcs** [comment]
I just published 1.4.0

**Comment by kalamcs** [comment]
Thanks @johnjbarton for giving the permissions.

**Comment by daKmoR** [comment]
woop woop - awesome 🎉🎉
thx 🤗

**Comment by wmhilton** [comment]
❤️
