### ISSUE TITLE
Missing GitHub tags/releases

### ISSUE THREAD

**Issue by XhmikosR** [karma-runner/karma-browserstack-launcher#153]
It seems tags >= v1.4.0 aren't pushed here. Could someone push them?

/CC @johnjbarton

**Comment by XhmikosR** [comment]
Ping @johnjbarton

**Comment by johnjbarton** [comment]
I pushed the tag for v1.4.0
The 1.5.0 and 1.5.1 versions were not released using the grunt release script and thus we don't know what commit they match.

**Comment by ckzgraphics** [comment]
@johnjbarton - The release tag v1.5.1 was rolled out by @kalamcs - [https://github.com/karma-runner/karma-browserstack-launcher/releases/tag/v1.5.1](https://github.com/karma-runner/karma-browserstack-launcher/releases/tag/v1.5.1)

I think we can close [this issue](https://github.com/karma-runner/karma-browserstack-launcher/issues/153).

**Comment by XhmikosR** [comment]
1.5.0 is missing too

**Comment by ckzgraphics** [comment]
Hi @XhmikosR - @kalamcs has updated the release for v1.5.0 => [https://github.com/karma-runner/karma-browserstack-launcher/releases](https://github.com/karma-runner/karma-browserstack-launcher/releases)

**Comment by XhmikosR** [comment]
Thanks! Please try to not miss this in the future since there's no changelog file.
