### ISSUE TITLE
Config option `tunnelIdentifier` has no effect

### ISSUE THREAD

**Issue by csvn** [karma-runner/karma-browserstack-launcher#155]
## Issue

The README.md says that `tunnelIdentifier` can be set to select the `localIdentifier` for the Browserstack Local connection. But [the code clearly shows](https://github.com/karma-runner/karma-browserstack-launcher/blob/master/index.js#L16-L20) that this setting is not used or passed to `browserstack-local`. I think this was broken in ea4ec78352d8829742ae3e96b42944f96d0174e8. 

Due to this, we can't set a [specific ID in the browser capabilities](https://www.browserstack.com/local-testing) (e.g. `capabilities['browserstack.localIdentifier'] = 'xxx'), because it's randomly created in `browserstack-local`.

## Our use case

We have a two CI jobs for tests, with different configurations. Both starts a Karma separately, but with different browsers setup and script bundling configuration. The issue is that one job keeps having jobs that says e.g. "Firefox 61.0 (Windows 10) has not captured in 60000 ms, killing.". I'm pretty sure this is with multiple Browserstack Local connections, they end up

**Comment by zarahzachz** [comment]
@csvn Any progress on this? My team is now experiencing the same problem ("Firefox 61.0 (Windows 10) has not captured in 60000 ms, killing.") for all our supported browsers.

**Comment by csvn** [comment]
@zarahzachz I've made a PR at #158, and we are currently running my fork via npm (`"karma-browserstack-launcher": "csvn/karma-browserstack-launcher#fix-configuration-options",). The maintainers need to look at the PR, merge, and release. I have nothing to add to my PR currently 🤷‍♂
