### ISSUE TITLE
Launcher fails to capture

### ISSUE THREAD

**Issue by kylewelsby** [karma-runner/karma-browserstack-launcher#17]
Been evaluating BrowserStack with Karma, but sadly I can not get any tests to run on the system.

BrowserStack appears to not properly connect to the browser, I would think the localTunnel feature is not working correctly.

```
INFO [karma]: Karma v0.12.31 server started at http://localhost:9876/
DEBUG [launcher.browserstack]: Establishing the tunnel on localhost:9876
INFO [launcher]: Starting browser ie 11 (WINDOWS 8.1) on BrowserStack
INFO [launcher]: Starting browser ie 10 (WINDOWS 8) on BrowserStack
DEBUG [launcher.browserstack]: Tunnel established.
DEBUG [launcher.browserstack]: ie 10 (WINDOWS 8) job queued with id 24519736.
DEBUG [launcher.browserstack]: ie 11 (WINDOWS 8.1) job queued with id 24519737.
INFO [launcher.browserstack]: ie 10 (WINDOWS 8) session at http://www.browserstack.com/automate/builds/ae6a21d5f4b13b1337e8c87839e0d394b80368fe/sessions/5e04d90574a37f0a88012155ba15d0370303a542
DEBUG [launcher.browserstack]: ie 10 (WINDOWS 8) job with id 24519736 still in queue.
INFO [launcher.browserstack]: ie 11 (WINDOWS 8.1) session at http://www.browserstack.com/automate/builds/ae6a21d5f4b13b1337e8c87839e0d394b80368fe/sessions/b07e8061bf29fec5ed7d5c5ba1857ad31d473ed2
DEBUG [launcher.browserstack]: ie 11 (WINDOWS 8.1) job with id 24519737 still in queue.
DEBUG [launcher.browserstack]: ie 10 (WINDOWS 8) job started with id 24519736
DEBUG [launcher.browserstack]: ie 11 (WINDOWS 8.1) job with id 24519737 still in queue.
DEBUG [launcher.browserstack]: ie 11 (WINDOWS 8.1) job started with id 24519737
WARN [launcher.browserstack]: ie 10 (WINDOWS 8) has not captured in 120000 ms, killing.
DEBUG [launcher.browserstack]: Killing ie 10 (WINDOWS 8) (worker 24519736).
DEBUG [launcher.browserstack]: ie 10 (WINDOWS 8) (worker 24519736) successfully killed.
WARN [launcher.browserstack]: ie 11 (WINDOWS 8.1) has not captured in 120000 ms, killing.
DEBUG [launcher.browserstack]: Killing ie 11 (WINDOWS 8.1) (worker 24519737).
DEBUG [launcher.browserstack]: ie 10 (WINDOWS 8) job queued with id 24519890.
DEBUG [launcher.browserstack]: ie 11 (WINDOWS 8.1) (worker 24519737) successfully killed.
INFO [launcher.browserstack]: ie 10 (WINDOWS 8) session at http://www.browserstack.com/automate/builds/ae6a21d5f4b13b1337e8c87839e0d394b80368fe/sessions/c959ec04e0202e45cb090ec60b6f572b918c4e64
DEBUG [launcher.browserstack]: ie 10 (WINDOWS 8) job with id 24519890 still in queue.
DEBUG [launcher.browserstack]: ie 11 (WINDOWS 8.1) job queued with id 24519906.
DEBUG [launcher.browserstack]: ie 10 (WINDOWS 8) job started with id 24519890
INFO [launcher.browserstack]: ie 11 (WINDOWS 8.1) session at http://www.browserstack.com/automate/builds/ae6a21d5f4b13b1337e8c87839e0d394b80368fe/sessions/e4019e7783fcd38fd5c9dc929f9b35f5c484c1ae
DEBUG [launcher.browserstack]: ie 11 (WINDOWS 8.1) job with id 24519906 still in queue.
DEBUG [launcher.browserstack]: ie 11 (WINDOWS 8.1) job started with id 24519906
```

**Comment by mjackson** [comment]
I'm currently experiencing this same issue. My tests run ok, but this launcher does not mark the tests as captured so it runs them again.

In case you'd like to investigate, you can see [my `karma.conf.js`](https://github.com/rackt/history/blob/master/karma.conf.js) and [the output from one of my builds](https://travis-ci.org/rackt/history/builds/73975820). If you look closely at the build output, you can see:

- The [tests pass on Firefox 32](https://travis-ci.org/rackt/history/builds/73975820#L435), but then [karma complains that it hasn't captured any output](https://travis-ci.org/rackt/history/builds/73975820#L446)
- The [tests pass on Chrome 39](https://travis-ci.org/rackt/history/builds/73975820#L437), but then [karma complains that it hasn't captured any output](https://travis-ci.org/rackt/history/builds/73975820#L445)

This pattern repeats for other browsers as well and leads to many duplicate requests being sent to BrowserStack to run tests that have already run.

This may be related to #26, but I'm not sure. Haven't had a chance to dive into the code.

@donato Do you have a minute to look into this?

**Comment by marian-r** [comment]
I ran into similar problems and contacted BrowserStack support. They said they are going to release a new version of local testing binaries which should fix this. I will let you know when I have any updates.

**Comment by d6u** [comment]
@marian-r Do they released that after 3 months?

**Comment by marian-r** [comment]
Oh yes, I forgot about this thread. They released new versions of binaries and made couple of other changes. But also, we made some changes to our code, so now I'm not sure what solved the problems, but for us it seems to be solved.

**Comment by d6u** [comment]
@marian-r Good to know. Thanks!

**Comment by Dignifiedquire** [comment]
@marian-r  can I close this then?

**Comment by marian-r** [comment]
Can @kylewelsby confirm that it is solved?

**Comment by joeyparrish** [comment]
FWIW, I had the same issue since upgrading to the latest version of the launcher.  Adding this to my config fixed it:

```
    browserStack: {
      startTunnel: true
    },
```

**Comment by lluisnieto** [comment]
I've just installed karma-browserstack-launcher and signed it for trial in browserstack. 
Configured my credentials but it keeps getting unable to connect when I run tests:

 [launcher.browserstack]: Can not establish the tunnel.
Error: child failed to start:
BrowserStackLocal v5.9

 *** Error: You provided an invalid key
