### ISSUE TITLE
captureTimeout option give no effect

### ISSUE THREAD

**Issue by phun-ky** [karma-runner/karma-browserstack-launcher#22]
I get these kind of errors a lot:

    WARN [launcher.browserstack]: chrome 39.0 (OS X Yosemite) has not captured in 60000 ms, killing

And to try to circumvent those errors, I've updated the karma-config like this:

    browserStack: {
      captureTimeout: 240, // default is 120
      timeout: 600, // default is 300
      retryLimit : 5
    },

But the capture timeout, as reflected in the error above, is the same (60000 ms)

**Comment by sford** [comment]
Hey @phun-ky , try setting `captureTimeout` outside of the `browserStack` config option. According to https://github.com/karma-runner/karma-browserstack-launcher/blob/master/index.js#L90, the `captureTimeout` setting is obtained from the normal karma config object.

**Comment by Dignifiedquire** [comment]
@phun-ky Is this still an issue?

**Comment by phun-ky** [comment]
I have not encountered these errors lately, but still, I have not used the launcher the last 3 months. Closed this. Please use it as a reference if this occurs for other users
