### ISSUE TITLE
Updating to package browsersack v1.1.1 causes EACCESS

### ISSUE THREAD

**Issue by phun-ky** [karma-runner/karma-browserstack-launcher#23]
Updating to the browserstack package v 1.1.1 causes a EACCESS error starting from line 144 in browserstackTunnel.js: `this.tunnel = spawn(binary.command, binary.args.concat([options.key]).concat(params));`

https://github.com/pghalliday/node-BrowserStackTunnel/blob/master/src/BrowserStackTunnel.js#L144

I had to roll back to `~1.0` for browserstack to make the `karma-browserstack-launcher` to work

ref: https://github.com/karma-runner/karma-browserstack-launcher/commit/3527eb6c6392e401ae745c0e0f6e13f5c183634d

ref: https://github.com/scottgonzalez/node-browserstack/issues/31

**Comment by Dignifiedquire** [comment]
Is this still an issue?

**Comment by phun-ky** [comment]
I have not encountered these errors lately, but still, I have not used the launcher the last 3 months. Closed this. Please use it as a reference if this occurs for other users
