### ISSUE TITLE
Revert real_mobile on 0.1.x

### ISSUE THREAD

**Issue by mzgol** [karma-runner/karma-browserstack-launcher#33]
The commit https://github.com/karma-runner/karma-browserstack-launcher/commit/85c4764199c9c78c7a725385d055b9d1293f6272 shouldn't have landed in a patch release as it's a breaking change.

The `true` default is IMO wrong - BrowserStack doesn't have all devices available as real mobiles so just updating the karma-browserstack-launcher makes a lot of browsers fail.

The default should be changed to `false`.

**Comment by donato** [comment]
@mzgol, care to review?

**Comment by mzgol** [comment]
@donato reviewed

**Comment by donato** [comment]
Published as a patch release, thanks!
