### ISSUE TITLE
Add limit for concurrent parallel tests

### ISSUE THREAD

**Issue by shaharmor** [karma-runner/karma-browserstack-launcher#56]
When running tests on multiple browsers (For example 20), browser stack will queue some of the browsers until you will have available vm's (depends on your account).

This makes karma wait forever.

It should be possible to add a config to set how many concurrent browsers will be run in parallel, and wait until they finished before running the next ones.

**Comment by shaharmor** [comment]
Nevermind, found it exists in karma itself

**Comment by lddubeau** [comment]
For the sake of those who land here while doing a search and probably don't know already: use the `concurrency` option of [Karma](https://karma-runner.github.io/1.0/config/configuration-file.html).

**Comment by aripalo** [comment]
It might be a good idea to document this on the `README`.

**Comment by ykhandor** [comment]
`concurrency` option does not take effect when I set it on my Karma Config:

`config.set({
        basePath: '',
        frameworks: ['parallel', 'jasmine'],
        concurrency: 4,
        exclude: [],
        files: [
            {
                pattern: './spec-bundle.js',
                watched: false
            },
            {
                pattern: '../../node_modules/moment/moment.js',
                watch: false
            }
        ].....`

Can someone please advise what am I missing here?
@lddubeau @dignifiedquire @joeljeske
