### ISSUE TITLE
Worker manager sometimes keeps the process open after all tests have completed

### ISSUE THREAD

**Issue by willfrew** [karma-runner/karma-browserstack-launcher#62]
Sometimes the worker manager carries on polling for updates after all tests have exited.
I did a little digging and confirmed that it was the `setTimeout` / http requests that were keeping the process alive because of a race condition in the code to stop polling.

I didn't have time to create a PR but I added some logging statements at the following places:

A: `Shutting down the tunnel` [here](https://github.com/karma-runner/karma-browserstack-launcher/blob/master/index.js#L71)
B: `'workerManager.isPolling', workerManager.isPolling` [here](https://github.com/karma-runner/karma-browserstack-launcher/blob/master/index.js#L76)
C: `Started polling` [here](https://github.com/karma-runner/karma-browserstack-launcher/blob/master/worker-manager.js#L56)
D: `gotWorkers` [here](https://github.com/karma-runner/karma-browserstack-launcher/blob/master/worker-manager.js#L57-L58)
E: `'this._pollHandle', this._pollHandle` as the first line in [this method](https://github.com/karma-runner/karma-browserstack-launcher/blob/master/worker-manager.js#L85-L86)
F: `Stopping polling` inside [this block](https://github.com/karma-runner/karma-browserstack-launcher/blob/master/worker-manager.js#L87-L88)

And this is the trace when I see the worker manager fail to stop polling:
```
A: Shutting down the tunnel.
C: Started polling
B: workerManager.isPolling true
E: this._pollHandle { _called: true,
  _idleTimeout: 1000,
  _idlePrev: null,
  _idleNext: null,
  _idleStart: 24300,
  _onTimeout: [Function],
  _repeat: null
}
F: Stopping Polling
D: gotWorkers
C: Started polling
D: gotWorkers
C: Started polling
D: gotWorkers
```

I'll try to figure it out and come up with a PR, but for now I've just added `process.nextTick(function() { process.exit(0); });` to my code to work around this.

**Comment by shirish87** [comment]
Ran a bunch of tests trying to reproduce this. Haven't faced the issue so far.

**Comment by ajaykodali** [comment]
I think we are seeing this issue or something very similar. I started seeing this when running our tests on Jenkins, the tests are all executed and task seems to be finished but the process never exits. This is fairly reproducible in our Jenkins setup but I haven't been able to reproduce this locally.
