### ISSUE TITLE
Capabilities Support

### ISSUE THREAD

**Issue by dsuckau** [karma-runner/karma-browserstack-launcher#66]
Hey,

first thank you for the launcher! It works perfect for me. The only thing I am missing is, that it does not support all capabilities that are offered by BrowserStack:

https://www.browserstack.com/automate/capabilities

For example "browserstack.video" or "browserstack.debug". Especially "video" (true/false) would be very nice for me, to disable the video recording. BrowserStack says it would make the tests faster.

Are there any plans to implement it or are PRs desired?

Greets from Germany

**Comment by dignifiedquire** [comment]
I'll happily accept PRs :)

**Comment by JakeChampion** [comment]
I think #118 gets us part way there :-)

**Comment by RozennK** [comment]
The 'timezone' capability would also be useful for me.

**Comment by danielnaab** [comment]
I came across this while trying to use `browserstack.ie.compatibility`. Would it be reasonable to just pass all capabilities provided by the user verbatim, rather than handling each separate? Or perhaps provide an `extraCapabilities` attribute that functions that way?

**Comment by Pringels** [comment]
+1 on setting timezone. I agree with @danielnaab that being able to extend capabilities verbatim would be the ideal solution.
