### ISSUE TITLE
ERROR [reporter.browserlabs]: ? Could not update BrowserStack status

### ISSUE THREAD

**Issue by 4garfield** [karma-runner/karma-browserstack-launcher#85]
### Expected behaviour
there should be no error

### Actual behaviour
`12 12 2016 19:42:15.160:ERROR [reporter.browserlabs]: ? Could not update BrowserStack status`

### Environment Details

- Karma version: 1.3.0
- karma-browserstack-launcher version: 1.1.1
- using proxy to connect the browserstack server, has already set proxyHost, proxyPort in karma.conf.js

### Steps to reproduce the behaviour

after run karma start karma.conf.js

**Comment by 4garfield** [comment]
update debug log as below:
```
12 12 2016 19:54:57.280:ERROR [reporter.browserlabs]: ? Could not update BrowserStack status
12 12 2016 19:54:57.281:DEBUG [reporter.browserlabs]: { [Error: getaddrinfo ENOTFOUND www.browserstack.com]
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'www.browserstack.com' }
Error: getaddrinfo ENOTFOUND www.browserstack.com
    at errnoException (dns.js:44:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:94:26)
```

I assume it maybe I use the proxy to connect the browserstack, but the update session status function didn't support proxy?

**Comment by earnubs** [comment]
@4garfield yeah, the reporter doesn't seem to pass the proxy details to createAutomateClient, only the creds
